[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_FLAGS = "--version"
  NPM_VERBOSE = "true"
  VITE_APP_NAME = "Sri Ananth Hospital"
  NPM_CONFIG_PRODUCTION = "false"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"

# Required for SPA routing - handle all routes with index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-attr 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https:;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Cache control for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[dev]
  framework = "#custom"
  targetPort = 8080
  port = 8888
  publish = "dist"
  command = "npm run dev"
