[build]
  base = "/"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_FLAGS = "--version"
  NPM_VERBOSE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[dev]
  framework = "#custom"
  targetPort = 8080
  port = 8888
  publish = "dist"
  command = "npm run dev"
